### ISSUE TITLE
some errors

### ISSUE THREAD

**Issue by staycanuca** [TheAssassin/kodi-invidious-plugin#1]
Hi,
when I try to play video I get this:
 ERROR: CCurlFile::Stat - Failed: Timeout was reached(28) for https://invidio.us/api/manifest/dash/id/r7wzcYwPY1k

and other non-critical error is related to addon version:

ERROR: AddonVersion: alpha-1 is not a valid revision number

**Comment by TheAssassin** [comment]
This plugin is pretty much brand new. It was written mostly yesterday. Thanks for your early feedback.

> ERROR: AddonVersion: alpha-1 is not a valid revision number

Okay, we can fix that. Do you know whether Kodi provide any "naming guidelines"?

> ERROR: CCurlFile::Stat - Failed: Timeout was reached(28) for https://invidio.us/api/manifest/dash/id/r7wzcYwPY1k

Sometimes, the official Invidious instance (same goes for many others) can be overloaded resp. blocked by YouTube. Therefore, I made the Invidious instance configurable yesterday. You can set a different instance if https://invidio.us does not work.

![screenshot_2020-04-14_13-23-14](https://user-images.githubusercontent.com/4503202/79219807-3a140f80-7e53-11ea-9920-6170073f9717.png)

The error message you found is outside the scope of this plugin. I am using the awesome [inputstreamhelper addon](https://github.com/emilsvennesson/script.module.inputstreamhelper) to play adaptive streams. I have not found a way to provide any sort of "fallback stream URLs", which it should use if MPEG-DASH playback fails. Therefore, the only workaround as of yet is to use a different instance.

Please see https://github.com/omarroth/invidious/wiki/Invidious-Instances for a list of publicly available instances.

If possible, we might also just use youtube-dl instead of Invidious, at least for *some* tasks (e.g., playback of the streams), there is a Kodi addon for it already. That way, we do not create additional load on the Invidious instances. In this early state, though, Invidious is just fine.

From my experience with Invidious, I think the search functionality as well as other metadata-based operations are not blocked by Google, it's always only the video playback that yields those "instance might be blocked" errors from time to time.

**Comment by staycanuca** [comment]
Thank you.
Form version you can use this template: x.x.x
